name: "CI Run"
on:
  push:
    paths:
      - ".github/workflows/ci.yml"
      - "Dockerfile"
      - "dist/index.js"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Run the Action
        id: run-action
        uses: ./
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
          repository: CI
          tags: |
            latest
            anothertag
          buildArg: |
            THISISARG1=test
            THISISARG2=test

      - name: Run the Action
        id: run-action
        uses: ./
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
          tags: latest
          image_name: CI
          buildArg: |
            THISISARG1=test
            THISISARG2=test    

      - uses: craftech-io/slack-action@v1
        with:
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
