name: "Test Run"
on:
  push:
    paths:
      - ".github/workflows/test.yml"
      - "dist/index.js"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        if: github.repository == 'matootie/github-docker'
      - name: Run the Action
        id: run-action
        uses: ./
        with:
          accessToken: ${{ secrets.GITHUB_TOKEN }}
          context: checkrun
          buildArg: |
            HTTP_PROXY=http://10.20.30.2:1234
            FTP_PROXY=http://40.50.60.5:4567
      - name: Test output
        run: echo ${{ steps.run-action.outputs.imageURL }}
