name: "Test Run"
on:
  push:
    paths:
      - "dist/index.js"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        if: github.repository == 'matootie/github-docker'
      - name: Run the Action
        id: run-action
        uses: ./
        with:
          accessToken: ${{ secrets.GITHUB_TOKEN }}
          context: checkrun
      - name: Test output
        run: echo ${{ steps.run-action.outputs.imageURL }}
